include:
- ./__init__.py
- ./data_unify.py
- ./data-unify-requirements.txt
- ./data-unify-build.sh
kind: ArchiveUploadSpec
name: init---py-sKiD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: data-unify-2
spec:
  buildcmd: ./data-unify-build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://init---py-sKiD
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-15T12:40:23Z"
