apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: avgsentday
spec:
  createingress: false
  functionref:
    functionweights: null
    name: avg-sentiment
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sentiment/days/{dateFrom:[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]}/{dateTo:[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /sentiment/days/{dateFrom:[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]}/{dateTo:[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]}
