apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: gazaukraine
spec:
  createingress: false
  functionref:
    functionweights: null
    name: gaza-ukraine-sent
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /gaza-ukraine/platform/{platform:[a-zA-Z0-9]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /gaza-ukraine/platform/{platform:[a-zA-Z0-9]+}
