apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: wordfreqplatform
spec:
  createingress: false
  functionref:
    functionweights: null
    name: word-frequency
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /wordfreq/platform/{platform:[a-zA-Z0-9]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /wordfreq/platform/{platform:[a-zA-Z0-9]+}
