include:
- ./__init__.py
- ./bluesky-processor.py
- ./bluesky-processor-requirements.txt
- ./bluesky-processor-build.sh
kind: ArchiveUploadSpec
name: init---py-JmgH

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bluesky-processor
spec:
  buildcmd: ./bluesky-processor-build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://init---py-JmgH
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-15T12:40:20Z"
