apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: bluesky-processor
spec:
  createingress: false
  functionref:
    functionweights: null
    name: bluesky-processor
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /bluesky-processor
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /bluesky-processor
